# Probability & Odds

## Probability:

$p \in [0,1]$

 $p \sim \frac{\#successes}{\#trials}$

In [1]:
import numpy as np

In [2]:
foo = np.random.randint(50, size = (10,5))
foo

array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [37, 47, 40, 27, 39],
       [ 7,  6, 10, 27, 11]])

In [3]:
(foo < 10)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [ True, False,  True, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False]], dtype=bool)

In [5]:
(foo < 10).all(axis=0)

array([False, False, False, False, False], dtype=bool)

In [6]:
mask = (foo < 10).any(axis=1)
mask

array([False, False,  True,  True,  True,  True,  True,  True, False,  True], dtype=bool)

In [7]:
foo[mask]

array([[43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [ 7,  6, 10, 27, 11]])

In [8]:
foo[[1, 0, 3, 1]]

array([[27, 42, 11, 25, 15],
       [40, 10, 17, 14, 15],
       [ 3, 42,  9, 22, 38],
       [27, 42, 11, 25, 15]])

In [9]:
foo

array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [37, 47, 40, 27, 39],
       [ 7,  6, 10, 27, 11]])

In [12]:
foo[1:-1:2]

array([[27, 42, 11, 25, 15],
       [ 3, 42,  9, 22, 38],
       [49,  1, 47, 10, 28],
       [ 5, 35, 19, 15, 29]])

In [13]:
column_mask = (foo < 10).any(axis=0)

In [14]:
column_mask

array([ True,  True,  True, False,  True], dtype=bool)

In [16]:
foo[column_mask]

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 5
  if __name__ == '__main__':


array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [41, 41,  9, 25, 35]])

In [ ]:
foo

In [20]:
bar = np.arange(10).reshape(10,1)
bar.shape

(10, 1)

In [24]:
np.concatenate((foo, bar[:5].reshape(1,5)), axis=0)

array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [37, 47, 40, 27, 39],
       [ 7,  6, 10, 27, 11],
       [ 0,  1,  2,  3,  4]])

In [25]:
np.hstack((foo,bar))

array([[40, 10, 17, 14, 15,  0],
       [27, 42, 11, 25, 15,  1],
       [43,  3, 26, 48,  7,  2],
       [ 3, 42,  9, 22, 38,  3],
       [41, 41,  9, 25, 35,  4],
       [49,  1, 47, 10, 28,  5],
       [10,  4, 29, 42,  9,  6],
       [ 5, 35, 19, 15, 29,  7],
       [37, 47, 40, 27, 39,  8],
       [ 7,  6, 10, 27, 11,  9]])

In [26]:
np.vstack((foo,bar[:5].reshape(1,5)))

array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [37, 47, 40, 27, 39],
       [ 7,  6, 10, 27, 11],
       [ 0,  1,  2,  3,  4]])

In [27]:
np.column_stack((foo, bar))

array([[40, 10, 17, 14, 15,  0],
       [27, 42, 11, 25, 15,  1],
       [43,  3, 26, 48,  7,  2],
       [ 3, 42,  9, 22, 38,  3],
       [41, 41,  9, 25, 35,  4],
       [49,  1, 47, 10, 28,  5],
       [10,  4, 29, 42,  9,  6],
       [ 5, 35, 19, 15, 29,  7],
       [37, 47, 40, 27, 39,  8],
       [ 7,  6, 10, 27, 11,  9]])

In [28]:
foo

array([[40, 10, 17, 14, 15],
       [27, 42, 11, 25, 15],
       [43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [37, 47, 40, 27, 39],
       [ 7,  6, 10, 27, 11]])

In [29]:
mask2 = foo.min(axis=1) < 10
mask2

array([False, False,  True,  True,  True,  True,  True,  True, False,  True], dtype=bool)

In [30]:
foo[mask2]

array([[43,  3, 26, 48,  7],
       [ 3, 42,  9, 22, 38],
       [41, 41,  9, 25, 35],
       [49,  1, 47, 10, 28],
       [10,  4, 29, 42,  9],
       [ 5, 35, 19, 15, 29],
       [ 7,  6, 10, 27, 11]])